#pragma config(Motor,  motorB,          L,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          R,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	int i;
	for(i=0;i<4;i++){
		moveMotorTarget(motorB, 1100,50);
		moveMotorTarget(motorC, 1100,50);
		waitUntilMotorStop(motorB);
		waitUntilMotorStop(motorC);
		moveMotorTarget(motorB, 240,50);
		moveMotorTarget(motorC, 240,-50);
		waitUntilMotorStop(motorB);
		waitUntilMotorStop(motorC);
	}
}
