#pragma config(Motor,  motorB,          L,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          R,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int i;
	for(i=0; i<10; i++){
		motor(motorB)=60;
		motor(motorC)=60;
		wait1Msec(2000);
		motor(motorB)=60;
		motor(motorC)-=60;
		wait1Msec(2000);

	}
}
