#pragma config(Sensor, S1,     T,              sensorEV3_Touch)
#pragma config(Sensor, S2,     G,              sensorEV3_Gyro)
#pragma config(Sensor, S3,     C,              sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     U,              sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          L,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          R,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSpeed(motorB,50);
	setMotorSpeed(motorC,50);
	while(SensorValue[T]== 0){};
	setMotorSpeed(motorB,0);
	setMotorSpeed(motorC,0);

}
